# Generated by Django 3.2.8 on 2021-10-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneplanetApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genotype',
            name='id',
        ),
        migrations.AlterField(
            model_name='genotype',
            name='chrom_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
